# Generated by Django 5.1.3 on 2024-12-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0002_message_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
